### ISSUE TITLE
Error on Custom Properties in `oklch()`

### ISSUE THREAD

**Issue by ai** [fpetrakov/stylelint-gamut#15]
We have a valid CSS code:

```css
.root {
  @supports (color: oklch(0% 0 0)) {
    background-color: oklch(var(--oklch-primary) / var(--alpha-bg));
  }
}
```

Of course, `var()` can’t be supported by `stylelint-gamut`. I suggest ignoring these rules.

But now plugin throw an error:

```
TypeError: undefined not allowed for Lightness in oklch()
    at /home/ai/Dev/evilmartians.com/src/components/Button/Button.module.css:89:5
```
