### ISSUE TITLE
Add Custom Properties support

### ISSUE THREAD

**Issue by ai** [fpetrakov/stylelint-gamut#5]
I found that rule works only for `background`, but doesn’t work for CSS Custom Properties. In modern world of design systems, all colors are set by [custom properties](https://github.com/evilmartians/oklch-picker/blob/main/view/base/index.css).

```css
:root {
  --color: oklch(57.35% 0.239 30);
}
```
